### PR TITLE
added withArmFpu to build node for a specific arm fpu

### PR DESCRIPTION
**Pull request by ariken74**
Hello there! 
The FPU instruction implementation on ARM cpu can vary and even being partial. (https://embeddedartistry.com/blog/2017/10/11/demystifying-arm-floating-point-compiler-options/)
For this reason our device using a SAMA5D3 cpu is not able to run node binaries compiled with the default configure options. (https://github.com/nodejs/node/issues/28906)
So I added the ability to specify the arm fpu variant on the pkg-fetch command line.

In the process I also added the option to use ninja to speed up the build time. But honestly I never been able to build successfully node with ninja :D

Thank you
Andrea

### CODE REVIEW

**Comment by robertsLando** [comment]
Instead of this, couldn't you simply add the ability to pass custom args?

**Comment by ariken74** [comment]
Because there is already a pull request for that and is 2 years old. Also I think is wise to guide the user on the possible options instead of letting them to play with unpredictable results.
If you think there are other useful parameters that can be implemented I will be happy to do that.

**Comment by robertsLando** [comment]
If you mean [this](https://github.com/vercel/pkg-fetch/pull/102) pr I think it makes sense to merge that instead of this, we don't have any plan to keep this "special" usage maintained so having options could lead users to ask us why at a cetain point it stops working

**Comment by ariken74** [comment]
If maintain means approve a pull request after 2 years... Anyway make more sense to use an ENV variable to pass the parameters. So I will close this PR.

**Comment by robertsLando** [comment]
@ariken74 I agree with you about the "maintain" statement but unfortunately this doesn't depend on me, I haven't the privileges to do so much and the guy who has is almost inactive in last month, also I don't work at Vercel I'm just a contributor that uses this package and I try to help where I can

**Pull request closed without merging**
