### PR TITLE
patches: bump to 14.20.1, 16.17.1, and 18.9.1

### PR DESCRIPTION
**Pull request by emahfoud**
related to https://github.com/vercel/pkg-fetch/issues/257

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]

**Review by jesec — COMMENTED** [review]
Thanks for the PR. LG2M in general.

Have you run the patches to ensure there is no delta/conflict?

**Comment by emahfoud** [comment]
I ran `yarn start --node-range node16 --arch x64 --output dist` for `14, 16, and 18` on windows and it generated artifacts and checksums without errors. Is that what you meant? Are there test suites I should run?

**Comment by emahfoud** [comment]
Those are the tests I'm aware of (they're run in the pipeline for the PR)
https://github.com/vercel/pkg-fetch/actions/runs/3163215418

**Comment by emahfoud** [comment]
@jesec Is there anything else I should do?

**Comment by jesec** [comment]
I was on a business trip last two weeks. Thanks for your patience. 

> I ran `yarn start --node-range node16 --arch x64 --output dist` for `14, 16, and 18` on windows and it generated artifacts and checksums without errors. Is that what you meant? Are there test suites I should run? And should I generate artifacts for all platforms before doing that?
> 

I want to make sure that the patches are perfectly applied. Check if there is something like "applied with offset" in the log. 

> I assumed the workflow to be like this:
> 
> * submit the PR
> * Merge approved PR (_to be done by someone with write access_)
> * Get the artifacts generated by the pipeline
> * Generate the hashes for these artifacts and commit them to the `expected.ts`
> * Send another PR to update the the hashes
> * Create a new release (_to be done by someone with write access_)
> 
> Is that correct?

I will do other steps.

**Comment by baparham** [comment]
@emahfoud this can probably be closed since it's covered by #260 and #269

**Comment by baparham** [comment]
I'm glad someone else is pushing patches to this project too :-) Thanks for the contributions!

**Pull request closed without merging**
