### PR TITLE
resolves #165 build Alpine x64 binaries

### LINKED ISSUE #165: Alpine binaries not available on 3.x
Hello,

I noticed that Alpine binaries are not available when using `pkg-fetch` 3.0.1:

```
$ npx pkg-fetch@3.0.1 -n node10 -p alpine -a x64
npx : 31 installé(s) en 3.363s
  fetched-v10.24.1-alpine-x64  [                    ] 0%
> Error! 404
> Not found in remote cache:
  {"tag":"v3.0","name":"node-v10.24.1-alpine-x64"}
> Building base binary from source:
  built-v10.24.1-alpine-x64
> Error! Not able to build for 'alpine' here, only for 'linux'
```

Here's the same command with `pkg-fetch` 2.6.0:

```
$ npx pkg-fetch@2.6.0 -n node10 -p alpine -a x64
  fetched-v10.15.3-alpine-x64  [====================] 100%
> /home/guillaume/.pkg-cache/v2.6/fetched-v10.15.3-alpine-x64
```

Is it intended? is there a workaround?

Thanks!

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #165

### CODE REVIEW

**Review by robertsLando — CHANGES_REQUESTED** [review]
This will definetly take more then one day to complete and github limit is about 6h. The code looks good but we should find a solution to this. I would make the node version an input of workflow dispatch so we could build this one by one if needed. @jesec toughts?

**Comment by Mogztter** [comment]
Thanks for your review @robertsLando 

> This will definetly take more then one day to complete and github limit is about 6h. 

Indeed, it took forever on my machine. Do you know why it "only" takes between 1 and 2 hours on Linux, Windows and macOS? In other words, why is it 10-20x times slower on Alpine?

> The code looks good but we should find a solution to this. 

I agree, do you have any hints that I could explore/try?

**Comment by robertsLando** [comment]
> I agree, do you have any hints that I could explore/try?

As I said the only way would be to remove the matrix and build just one for time and use the workflow dispatch inputs to define the node version. Hopefully the build will take less then 6h.

It takes forever because docker buildx uses qemu, emulated archs are slower. Dunno if there is a way like what we are doing for arm64 to cross biild them, @jesec could answer to this

**Comment by Mogztter** [comment]
Got it!

I just found https://github.com/oznu/alpine-node (which is also using qemu) and the build is relatively fast around 1 hour according to: https://github.com/oznu/alpine-node/actions?query=event%3Arelease

**Comment by robertsLando** [comment]
Let's try with that so!

**Comment by jesec** [comment]
This particular revision simply does not build for arm64. So emulation is not involved for now.

We do need to find a way to build for arm64. If we don’t have a native machine, cross compilation is the only viable option.

**Comment by jesec** [comment]
> Got it!
> 
> For reference, I just found https://github.com/oznu/alpine-node (which is also using qemu) and the build is relatively fast around 1 hour according to: https://github.com/oznu/alpine-node/actions?query=event%3Arelease

LOL. It cheats!

https://github.com/oznu/alpine-node/blob/d81366d372ccee39158dafd7098843f60f187eb8/.github/workflows/build-arm.yml#L27-L39

**Comment by Mogztter** [comment]
> LOL. It cheats!

Ah ah ah! 😆 

> This particular revision simply does not build for arm64. So emulation is not involved for now.
We do need to find a way to build for arm64. If we don’t have a native machine, cross compilation is the only viable option.

Correct, I'm only building for amd64.
I guess we can add build for arm64 in a follow up pull request no?

Here's the result: https://github.com/Mogztter/pkg-fetch/actions/runs/738423240

**Comment by jesec** [comment]
> > LOL. It cheats!
> 
> Ah ah ah! 😆
> 
> > This particular revision simply does not build for arm64. So emulation is not involved for now.
> > We do need to find a way to build for arm64. If we don’t have a native machine, cross compilation is the only viable option.
> 
> Correct, I'm only building for amd64.
> I guess we can add build for arm64 in a follow up pull request no?
> 
> Here's the result: https://github.com/Mogztter/pkg-fetch/actions/runs/738423240

A cross-compile capable workflow could be very different from a native-only one.

**Comment by jesec** [comment]
Unfortunately, Alpine does not provide official cross toolchains. There are third party ones (e.g. https://hub.docker.com/r/muslcc/x86_64), though.

However, due to the binary compatibility concerns (#124), it is not safe to use them to build shared(-linked) binaries, as there is no guarantee that those binaries would work on official Alpine. (It is OK to use them to build fully static binaries, though.)

The safe way here is to build with the official toolchain. But we don't have a native arm64 machine, and it is simply not possible to complete the build within 6 hours with the performance penalty of emulation.

**Comment by jesec** [comment]
Maybe you can try muslcc toolchains. If they work with official Alpine, we can use them. 

Check out https://github.com/jesec/pkg-fetch/blob/master/Dockerfile.linuxstatic if you need some inspiration.

**Comment by jesec** [comment]
Superseded by #168.

**Pull request closed without merging**
