### PR TITLE
Add support for 14.16.0

### LINKED ISSUE #117: Please create patch for 14.16.0
I tried using the 14.4.0 file to patch 14.16.0. I got the following error:
patching file src/node_main.cc
Hunk #1 FAILED at 20.
Hunk #2 succeeded at 82 (offset 12 lines).
Hunk #3 succeeded at 136 (offset 12 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/node_main.cc.rej
patching file src/node_options.cc
Hunk #1 succeeded at 230 (offset -3 lines).
> Error! Error: patch failed with code 1
    at ChildProcess.<anonymous> (D:\workdir\aws\pkg-fetch\lib-es5\spawn.js:68:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

Please support 14.16.0.

### PR DESCRIPTION
**Pull request by david-mohr**
Updated patch for 14.16.0

Closes #117

### CODE REVIEW

**Review by leerob — APPROVED** [review]

**Comment by leerob** [comment]
Thank you!

**Comment by david-mohr** [comment]
Happy to help @leerob. Could you please kick off a build so that the new binaries are in Releases?

**Comment by bfivelson** [comment]
Hi I am having an issue trying to build win64 binaries. This is my first time so I am sure I am doing something wrong 

I have downloaded node build tools
I have checked out node v14.16.0
I have put the path file in the the node dir and i get the following when i try to apply

git apply node.v14.16.0.cpp.patch
node.v14.16.0.cpp.patch:186: trailing whitespace.
'use strict';
node.v14.16.0.cpp.patch:187: trailing whitespace.

node.v14.16.0.cpp.patch:188: trailing whitespace.
const {
node.v14.16.0.cpp.patch:189: trailing whitespace.
  prepareMainThreadExecution
node.v14.16.0.cpp.patch:190: trailing whitespace.
} = require('internal/bootstrap/pre_execution');
error: corrupt patch at line 606




I add a line return at the end of the file and now I get 




git apply node.v14.16.0.cpp.patch
node.v14.16.0.cpp.patch:186: trailing whitespace.
'use strict';
node.v14.16.0.cpp.patch:187: trailing whitespace.

node.v14.16.0.cpp.patch:188: trailing whitespace.
const {
node.v14.16.0.cpp.patch:189: trailing whitespace.
  prepareMainThreadExecution
node.v14.16.0.cpp.patch:190: trailing whitespace.
} = require('internal/bootstrap/pre_execution');
error: patch failed: deps/v8/include/v8.h:9525
error: deps/v8/include/v8.h: patch does not apply
error: patch failed: deps/v8/src/api/api.cc:927
error: deps/v8/src/api/api.cc: patch does not apply
error: patch failed: deps/v8/src/codegen/compiler.cc:2045
error: deps/v8/src/codegen/compiler.cc: patch does not apply
error: patch failed: deps/v8/src/objects/js-objects.cc:5524
error: deps/v8/src/objects/js-objects.cc: patch does not apply
error: patch failed: deps/v8/src/objects/shared-function-info-inl.h:493
error: deps/v8/src/objects/shared-function-info-inl.h: patch does not apply
error: patch failed: deps/v8/src/parsing/parsing.cc:42
error: deps/v8/src/parsing/parsing.cc: patch does not apply
error: patch failed: deps/v8/src/snapshot/code-serializer.cc:409
error: deps/v8/src/snapshot/code-serializer.cc: patch does not apply
error: patch failed: lib/internal/bootstrap/pre_execution.js:9
error: lib/internal/bootstrap/pre_execution.js: patch does not apply

git status
HEAD detached at v14.16.0
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        node.v14.16.0.cpp.patch

nothing added to commit but untracked files present (use "git add" to track)



Thank you!

**Comment by bfivelson** [comment]
I ran this command which seemed to produce a better result

git apply --reject --whitespace=fix node.v14.16.0.cpp.patch

I will try and build now

**Comment by bfivelson** [comment]
I got these errors 

  node_contextify.cc
node\src\node_contextify.cc(765): error C2039: 'EnableCompilationForSourcelessUse': is not a member of 'v8::V8' [node\libnode.vcxproj]
  node\deps\v8\include\v8.h(9600): note: see declaration of 'v8::V8'
node\src\node_contextify.cc(765): error C3861: 'EnableCompilationForSourcelessUse': identifier not found [node\libnode.vcxproj]
node\src\node_contextify.cc(787): error C2039: 'FixSourcelessScript': is not a member of 'v8::V8' [node\libnode.vcxproj]
  node\deps\v8\include\v8.h(9600): note: see declaration of 'v8::V8'
node\src\node_contextify.cc(787): error C3861: 'FixSourcelessScript': identifier not found [node\libnode.vcxproj]
node\src\node_contextify.cc(818): error C2039: 'DisableCompilationForSourcelessUse': is not a member of 'v8::V8' [node\libnode.vcxproj]
  node\deps\v8\include\v8.h(9600): note: see declaration of 'v8::V8'
node\src\node_contextify.cc(818): error C3861: 'DisableCompilationForSourcelessUse': identifier not found [node\libnode.vcxproj]

**Comment by bfivelson** [comment]
moved to #112

**Comment by david-mohr** [comment]
@bfivelson have you tried using plain `patch`? I have successfully built windows binaries, they are in my fork as release 2.7

**Comment by bfivelson** [comment]
@david-mohr Thank you, so much for this!

I have not, where can I find information on the plain patch?

**Comment by david-mohr** [comment]
https://github.com/vercel/pkg-fetch/blob/master/lib/build.js#L38-L48

```
patch -p1 -i /path/to/the.patch
```

You should get a copy of `patch` on Windows when you install git-bash

**Comment by bfivelson** [comment]
@david-mohr  Thank you so much for all your help with this !

**Pull request merged**
