### PR TITLE
patches: bump to 19.8.1

### PR DESCRIPTION
**Pull request by baparham**

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
@baparham I'm not a master in patches but for what I can see it looks goot to me, tried to test the result patch ?

**Comment by baparham** [comment]
I am not confident with this patch. I tried upgrading to it with a project that was using node18, and it hits this issue:
```
node:internal/bootstrap/loaders:363
  if (!mod) throw new TypeError(`Missing internal module '${id}'`);
            ^

TypeError: Missing internal module 'internal/modules/cjs/helpers'
    at requireBuiltin (node:internal/bootstrap/loaders:363:19)
    at pkg/prelude/bootstrap.js:1887:10
    at pkg/prelude/bootstrap.js:1986:3
    at pkg/prelude/bootstrap.js:2259:3
    at readPrelude (node:internal/bootstrap/pkg:31:12)
    at node:internal/bootstrap/pkg:36:18
    at node:internal/bootstrap/pkg:43:4
    at node:internal/bootstrap/pkg:44:2
```

but I'm not sure what's related to upgrading from node18 to node19 in my client application, or what's related to a bad patch. This error makes me believe that this is in the node patches rather than in my userspace code.

I think this needs more tests, so perhaps this shouldn't block a release. However, I have no idea if this issue affects the older node19 patches as well.

**Comment by baparham** [comment]
ugh, I completely forgot that I also need https://github.com/vercel/pkg/pull/1862/files for this to work. Good opportunity to test that patch out I guess!!

**Comment by baparham** [comment]
> ugh, I completely forgot that I also need https://github.com/vercel/pkg/pull/1862/files for this to work. Good opportunity to test that patch out I guess!!

works now 🙄 so I think this can be merged

**Pull request merged**
