### PR TITLE
Allow to skip upload when GITHUB_TOKEN is not present

### PR DESCRIPTION
**Pull request by jesec**
This change allows users to distribute binaries via other means.

### CODE REVIEW

**Comment by jesec** [comment]
> @jesec Based on our last discussion I think we should completely remove the upload part from that script, right?

Yes. I would prefer that. But technically that would be a breaking change, and I am not sure if there are people who depend on that.

**Comment by jesec** [comment]
This change tries to not break the old behavior. If the `GITHUB_TOKEN` is there, fine, the script will proceed to upload the binaries to Github Releases automatically. If the `GITHUB_TOKEN` is not there, the binaries will be placed to `./dist` folder. 

Things can get pretty complicated. We may have to use Dockerfile-scripts to build binaries on a specific sysroot/base. We may want to do one build per job/machine, but upload all binaries at the same time. We may want to validate binaries (against `pkg` tests, for instance) before actually upload them. We may want to coordinate Releases. We may want to sign the binaries. And so on.

**Comment by jesec** [comment]
> > Yes. I would prefer that. But technically that would be a breaking change, and I am not sure if there are people who depend on that.
> 
> Just make a major release in that case, but before that we should sort out the binaries workflow

Yeah. Good point.

**Comment by robertsLando** [comment]
Also this is already included in #135 BTW

**Comment by jesec** [comment]
> Also this is already included in #135 BTW

As I said, that one is getting too bloated and needs to be split. 

So, per our discussions, I will bump the major and remove the auto-upload/release functions. We can then add "Upload Release Assets" jobs to the CI workflow, instead.

**Pull request closed without merging**
