### PR TITLE
Added support for Node 10 LTS

### PR DESCRIPTION
**Pull request by danielgindi**

### CODE REVIEW

**Comment by danielgindi** [comment]
@igorklopov It's about time to support node 10.15.3...

**Comment by igorklopov** [comment]
An interesting approach. I'll look soon. Thanks!

**Comment by peakji** [comment]
Is there any update on this PR? The current release (`v2.5.8`) is actually broken: https://github.com/zeit/pkg-fetch/issues/64.

**Comment by danielgindi** [comment]
I actually don't know if it's broken or not, but binaries are not supplied for 10.15.3 so it looks like they didn't manage to compile with the current patch... My patch is tested to compile though it may have other untested issued.
@igorklopov Are you having trouble compiling node 10.15.3 with your patch?

**Comment by kleggas** [comment]
Actually the current 10.15.3 patch is not broken, I built 10.15.3 with it for Linux x64, Linux arm64, Linux armv7. I then used each of them to build binaries on my windows, copied over the binaries to their respective target platform and they all worked as expected. I just think people are not building binaries for each target platform when there is a patch. I did have to edit the "/usr/lib/node_modules/pkg/node_modules/pkg-fetch/patches/patches.json" to point out correct version so it didn't download the 10.4.1 instead of using my own 10.15.3 nodes from ~/.pkg-cache

I think the build command should allowed a specific version, not just "node10" if there are more versions, but that's another issue ;)

If anyone can help me how to upload the binaries for Linux x64/armv7/arm64 I will do so. I'm new to github.

That being said, I'm no C++ expert and cannot say if current patch or this patch is better/equal/anything. Just that the current is also working to build binaries, if someone wants to build with it.

**Comment by kleggas** [comment]
I now noticed people have had problems building 10.15.3 (in other open issues here). With the same patch I used to build successful packages (the current one, not this one in this PR). I built on devices with the correct cpu arch, not in qemu. Maybe that makes a difference?

**Comment by danielgindi** [comment]
@kleggas The "current" patch is later than this PR. I did not test it, but I tested this one... 
It just looks to me like testing the other one is not done, as it did not automatically build the artifacts. There are however build issues on multi-cpu systems for 10.15.3 which was reported by me in node issues and was fixed. Basically if you retry running the vcbuild.bat multiple times (the count of the cpus you have) - it will eventually build.

**Comment by danielgindi** [comment]
@kleggas The "current" patch is later than this PR. I did not test it, but I tested this one... 
It just looks to me like testing the other one is not done, as it did not automatically build the artifacts. There are however build issues on multi-cpu systems for 10.15.3 which was reported by me in node issues and was fixed. Basically if you retry running the vcbuild.bat multiple times (the count of the cpus you have) - it will eventually build.

**Comment by soumyakantiroychowdhury** [comment]
Any update on this?

**Comment by leerob** [comment]
Since active support has ended for Node 10, we will be moving forward to 12 and 14.

https://endoflife.date/nodejs

**Pull request closed without merging**
