### PR TITLE
Fully static linking

### PR DESCRIPTION
**Pull request by nickgrealy**
- Added ability to configure "fully static" linking when building
- Added documentation to readme.md

Hopefully closes https://github.com/zeit/pkg/issues/555

### CODE REVIEW

**Comment by nickgrealy** [comment]
Just created PR so it was "ready to go"... building locally atm.

**Comment by einsqing** [comment]
need

**Comment by awjreynolds** [comment]
Be extremely careful with full static linking as you are now including libraries with copy-left license agreements. Particularly Ubuntu distributions. This could get you into a huge amount of legal hot water.

**Comment by igorklopov** [comment]
This may need for `-static` component to be added to target naming scheme, like `node12-linux-x64-static` so that both original and fully static can coexist and be used separately.

**Comment by jesec** [comment]
We supports a fully static "linuxstatic" variant now. Just specify "linuxstatic" as the platform. 

Note that if you want to build/compile, you have to build on Alpine (musl libc), because it is not practical to statically link against GNU libc:

* GNU libc is licensed under LGPL, which is basically GPL with dynamic linking exceptions. Static linking does not fall under this exception. If statically linked to glibc, the whole executable becomes effectively GPL, which could subject your own codes to the requirements of GPL if you distribute the result executable of `pkg`.
* glibc is unreliable when statically linked, and the program would crash in certain cases, potentially due to NSS.

**Pull request closed without merging**
