### PR TITLE
Patch for Node 18.16.0

### PR DESCRIPTION
**Pull request by jose-p-rivera**
patches applying properly: 

image

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]

**Comment by baparham** [comment]
@jose-p-rivera you will need to update the patch such that there are no offsets when applying hunks, even if they succeed. If you work directy in the node.js repo like the readme proposes as a patch workflow, then when you diff the changes back into the patch file at the end, they will have the correct line numbers.

**Comment by baparham** [comment]
The tests catch this: https://github.com/vercel/pkg-fetch/actions/runs/4748065452/jobs/8440196816?pr=295#step:8:7

**Comment by baparham** [comment]
you can also manually edit the patch file to update the line numbers for the handful of hunks that are at the wrong offset

**Comment by jose-p-rivera** [comment]
thanks, lines updated, evidence updated on description.

**Comment by jose-p-rivera** [comment]
interesting, are you using node v18x branch for the tests?

**Comment by baparham** [comment]
pkg-fetch gets the tar archive for the _specific tag_ of the version it is attempting to compile against, so the failures probably come if you based your patch on the tip of the 18x branch rather than the v18.16.0 tag, but I'm not sure, maybe something else went wrong.

Did you use a node repo to generate the patch set, and if so, what SHA (in node.js repo) did you base it on?

**Comment by baparham** [comment]
you should be able to run the `applyPatches` command locally on your machine to run the patch application only. I recommend running it with `--quiet-extraction` also. e.g. `yarn applyPatches --node-range node18 --quiet-extraction`

**Comment by jose-p-rivera** [comment]
> pkg-fetch gets the tar archive for the _specific tag_ of the version it is attempting to compile against, so the failures probably come if you based your patch on the tip of the 18x branch rather than the v18.16.0 tag, but I'm not sure, maybe something else went wrong.
> 
> Did you use a node repo to generate the patch set, and if so, what SHA (in node.js repo) did you base it on?

ok let me download the tar file and apply patches there, I did it on nodev18x Branch. Thanks.

**Comment by baparham** [comment]
I recommend you get the node git tree rather than the tar, it makes actually applying the patches much more straightforward. see https://github.com/vercel/pkg-fetch#example-workflow-for-applying-patches-to-a-new-version-of-nodejs-18130

**Comment by jose-p-rivera** [comment]
> I recommend you get the node git tree rather than the tar, it makes actually applying the patches much more straightforward. see https://github.com/vercel/pkg-fetch#example-workflow-for-applying-patches-to-a-new-version-of-nodejs-18130

yes, I'm applying it from the node branch: 
image
 and locally all patches appear to be applied with no offsets. 

just did it again reverting all changes on node branch and got same results: 

image

I will put this one as Draft.

**Comment by baparham** [comment]
Hm, yeah, that's very odd. I can try and reproduce on my end as well.

Do you end up with a diff in the node repo after you apply the patches? Are you adding those diffs back to the original patch file?

**Comment by jose-p-rivera** [comment]
> Hm, yeah, that's very odd. I can try and reproduce on my end as well.
> 
> Do you end up with a diff in the node repo after you apply the patches? Are you adding those diffs back to the original patch file?
not really I just applied the patches. Did it work also from your side?

**Comment by NewEraCracker** [comment]
Hello,

Could you please re-do this against Node.js 18.16.1 (https://nodejs.org/en/blog/vulnerability/june-2023-security-releases) ?

Thanks.

**Pull request closed without merging**
