### PR TITLE
🚀 feat: add patch for node v12.8.3

### PR DESCRIPTION
**Pull request by n1ru4l**

### CODE REVIEW

**Comment by dio** [comment]
Nice, can we have v12.8.4? It has security fixes. https://nodejs.org/en/blog/vulnerability/september-2020-security-releases/

**Comment by n1ru4l** [comment]
@dio Feel free to send a PR.

**Comment by robertsLando** [comment]
@n1ru4l I think we could add it to our fork instead of this, that will for sure be more updated than this.

**Comment by n1ru4l** [comment]
@robertsLando I also noticed our fork already includes this patch, however, CI did build 12.18.1 instead of 12.18.3.

**Comment by robertsLando** [comment]
@n1ru4l We should also fork pkg for that

**Comment by robertsLando** [comment]
@n1ru4l I think it's something here: https://github.com/vercel/pkg-fetch/blob/master/lib/index.js#L33

**Comment by robertsLando** [comment]
Ok got it, you forgot to add the patch to patches.json [here](https://github.com/vercel/pkg-fetch/blob/master/patches/patches.json)

**Comment by n1ru4l** [comment]
closed in favor of https://github.com/vercel/pkg-fetch/pull/105

**Pull request closed without merging**
