### PR TITLE
build: fetch Node.js sources from tar.gz archive instead of Git

### PR DESCRIPTION
**Pull request by jesec**
Bug: #204, #212

For #212 use case, the user may place the source archive and its `.sha256sum` to `$PKG_CACHE_PATH/node` (by default, PKG_CACHE_PATH is `~/.pkg-cache`), if the network connection is restricted.

### CODE REVIEW

**Comment by jesec** [comment]
cc: @blami

**Review by robertsLando — COMMENTED** [review]
Just wondering if it could make sense to provide both ways instead of completely drop git?

**Comment by blami** [comment]
Thanks for heads up. I went with recommendation given in #212 and patch and pre-build my tarball outside `pkg` so I technically don't need this nor other patch to make certain bits of Node.js shared with OS anymore. I will close my PR - forgot about it.

@robertsLando That is what my patch #212 does and @jesec didn't like it.

**Review by robertsLando — APPROVED** [review]
Ok I don't want to prevent this being merged. I trust @jesec in his choice

**Comment by jesec** [comment]
The real aim of the PR is to deal with #204. I think it is better to be less reliant on the unmanaged packages on the system (in that case, `git`). It just happens to deal with #212 as well, with zero additional complexity.

**Pull request merged**
