### PR TITLE
fix: patch issues with workers

### LINKED ISSUE #282: Crash when using background worker with node.js 18.14.1 and later
I was using an own build binary with the pkg-fetch patches for node 18.12.1 (everything was fine)
No as a new patch is available for node 18.14.1 I again build my own binary and this causes some crashes.

I have an application which starts a background worker. With the patches for node 18.12.1 I can run the application fine. I I used the prebuild binary for node 18.14.1 I got a crash while starting the background worker.

<pre>
node:internal/assert:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at new NodeError (node:internal/errors:399:5)
    at assert (node:internal/assert:14:11)
    at prepareExecution (node:internal/process/pre_execution:89:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:41:3)
    at node:internal/bootstrap/pkg:7:1 {
  code: 'ERR_INTERNAL_ASSERTION'
}

Node.js v18.14.1
</pre>

Output of NODE_DEBUG=* set

[output.log](https://github.com/vercel/pkg-fetch/files/10954415/output.log)

The same issue happens also with node 18.14.2 patches in node.js 18.14.2

### PR DESCRIPTION
**Pull request by matthias-heller**
As described in https://github.com/vercel/pkg-fetch/issues/282 there is an issue with workers starting from node.js 18.14.1. This fix solves this issue for 18.15.0

Fixes #282

### CODE REVIEW

**Review by robertsLando — CHANGES_REQUESTED** [review]
Weel done @matthias-heller ! Wondering if the same fix should be applied also in other patches as well?

**Comment by robertsLando** [comment]
@baparham I don't remember if we have a ci setup to validate patches?

**Comment by baparham** [comment]
we have checks for applying patches (just that they apply cleanly) but what we lack are checks that the binaries actually build, and the built binaries run. This would also be a great example of having a test that used a node worker as well, to prove this works, and doesn't get broken again in the future.

We obviously lack the current infrastructure for us to expect that from this PR, but it's a thought for future improvements.

**Comment by matthias-heller** [comment]
Yeah I think it should be tested on 19.x I just saw the one file and compared it with 18.x and the file looks identical, so I would assume that the fix is needed on 19.x as well, but at the moment I won't find the time to test it with 19.x as well

**Comment by baparham** [comment]
See if you can add a commit for fixing 19.x as well, then we can kick off some builds to generate binaries that we can test with. I think if that goes well we can merge this in

**Comment by baparham** [comment]
@matthias-heller you mean to close this?

**Comment by baparham** [comment]
Nm, i see it over in #288

**Pull request closed without merging**
