### PR TITLE
update version in package.json

### PR DESCRIPTION
**Pull request by N0Cloud**
prebuild image are not found without updating the version in package.json.

### CODE REVIEW

**Comment by baparham** [comment]
oh good grief, I did a terrible job with this, haha. Thanks for fixing.

**Comment by N0Cloud** [comment]
@baparham also found an other issue. The [expected-shas.json](https://github.com/vercel/pkg-fetch/blob/main/lib/expected-shas.json) file need to be updated

**Comment by baparham** [comment]
you are correct! I'll push that here so we can just merge this once.

**Comment by baparham** [comment]
thanks for the early testing 🙏

**Review by baparham — APPROVED** [review]

**Pull request merged**
