### PR TITLE
patches: drop Node < 8 and old point releases

### PR DESCRIPTION
**Pull request by jesec**

### CODE REVIEW

**Comment by robertsLando** [comment]
I already did this on my pull #135

**Comment by jesec** [comment]
> I already did this on my pull #135

This branch is there since last week. 

#135 is becoming too bloated. We have to split changes to different commits and preserve proper authorship.

**Review by robertsLando — COMMENTED** [review]
LGTM

**Comment by jesec** [comment]
BTW: @leerob Please enable "Rebase and merge" option.

**Pull request merged**
