### PR TITLE
Update patches for v16.20.2 and v18.17.1

### PR DESCRIPTION
**Pull request by jcoglan**
This rebases the v16 and 18 patches for the recent security releases v16.20.2 and v18.17.1. I've not changed the patch content at all, I have just rebased them from the original tag onto the new ones in the nodejs/node repo.

### CODE REVIEW

**Comment by matthias-heller** [comment]
@jcoglan: Thanks for providing the patches. I tried out the patch for version 18.17.1 and in our environments it is working perfectly fine, with workers and also without.

**Comment by SucculentGoose** [comment]
Are there any updates to getting this merged and a new version of pkg-fetch and pkg being released?

**Comment by jcoglan** [comment]
Just to highlight something related to this: `pkg` depends on a fixed version of `pkg-fetch`, which means updates to `pkg-fetch` do not automatically propagate to `pkg` users. I'm not sure why this is, but the dependency would need to be loosened for most users to benefit from this.

**Comment by chendricks** [comment]
Just wanted to also vote for merging this as we're eagerly wanting to upgrade to node 18.17.1 because it fixes a critical security vulnerability.

**Comment by Kerry-Lee** [comment]
We are also in need of this node version 18 patch bump. 🙏

**Comment by robertsLando** [comment]
I'm going to create a custom fork of both pkg and pkg-fetch on https://github.com/yao-pkg

**Comment by baparham** [comment]
Seems reasonable. I've had zero time to pay attention to pkg and I
understand the need to have security releases ASAP.

**Comment by robertsLando** [comment]
For anyone that is enterested in this project, giving that I don't receive any feedback from Vercel anymore, I created my own forks of both pkg and pkg-fetch:

[yao-pkg/pkg-fetch](https://github.com/yao-pkg/pkg-fetch)
[yao-pkg/pkg](https://github.com/yao-pkg/pkg)

If someone is interested in helping me create a PR or move your active PR to those repositories.

Thanks 🙏🏼

**Pull request closed without merging**
