### PR TITLE
CI: output to dist/ with "node-*" prefix

### PR DESCRIPTION
**Pull request by jesec**

### CODE REVIEW

**Review by robertsLando — COMMENTED** [review]
Just for info why `node-` prefix and not `fetched` ?

**Comment by jesec** [comment]
> Just for info why `node-` prefix and not `fetched` ?

Because they are binaries to be uploaded.

**Comment by robertsLando** [comment]
@jesec Sorry I mean `uploaded-`, AFAIK pkg looks for that?

**Comment by jesec** [comment]
> @jesec Sorry I mean `uploaded-`, AFAIK pkg looks for that?

See #149.

**Review by robertsLando — APPROVED** [review]
Forgot that. Sorry, LGTM

**Pull request merged**
