### PR TITLE
Add workflows for Alpine binaries and fully static Linux binaries

### PR DESCRIPTION
**Pull request by jesec**
https://github.com/jesec/pkg-fetch/actions/runs/750738112

https://github.com/jesec/pkg-fetch/actions/runs/750738080

https://github.com/jesec/pkg-fetch/actions/runs/750738018

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
Awesome @jesec ! LGTM

**Review by leerob — COMMENTED** [review]
Are there any test changes needed? I see they're passing.

**Comment by Mogztter** [comment]
Woot woot, thanks for taking care of it @jesec! 🎉

**Comment by jesec** [comment]
> Are there any test changes needed? I see they're passing.

I ran the binary workflows in my own repo, and they are all passing.

**Comment by jesec** [comment]
Workflows started:

win: https://github.com/vercel/pkg-fetch/actions/runs/752615557

macos: https://github.com/vercel/pkg-fetch/actions/runs/752615807

linux: https://github.com/vercel/pkg-fetch/actions/runs/752615173

linuxstatic: https://github.com/vercel/pkg-fetch/actions/runs/752615423

alpine: https://github.com/vercel/pkg-fetch/actions/runs/752615021

**Comment by jesec** [comment]
@leerob We are ready for a new release.

**Comment by Hypfer** [comment]
Would it be possible to also add static armv7 binaries?

I'm currently using a very broken fork of this repo because I need those to run on vacuum robots. Being able to use mainline pkg again would be nice

**Comment by leerob** [comment]
@jesec new release cut!

**Comment by jesec** [comment]
> @jesec new release cut!

Awesome!

However, the tag name is not what `pkg-fetch` expect. We have to append the changelog to `v3.0` tag and upload binaries there. If no one does it, I can do it after Wednesday (I am AFK right now due to some family things).

**Comment by leerob** [comment]
I don't understand why we have it set up that way. IMO pkg should always look at the latest release of pkg-fetch. It feels weird to keep updating a release. The release is supposed to be a snapshot in time.

**Comment by jesec** [comment]
> I don't understand why we have it set up that way. IMO pkg should always look at the latest release of pkg-fetch. It feels weird to keep updating a release. The release is supposed to be a snapshot in time.

We discussed this before: https://github.com/vercel/pkg-fetch/issues/155#issuecomment-816774226 : patch releases are not supposed to change binaries, and it is troublesome to unnecessarily upload binaries all over again to a new tag. 

Fetching from the `latest` is not very deterministic, as `latest` can be 3.0 today but 4.0 the next day. And, #169 can’t work with that.

**Comment by jesec** [comment]
Done. Retagged to `v3.0.2`, uploaded binaries to `v3.0` and appended changelogs.

**Comment by robertsLando** [comment]
@leerob I suggest to give @jesec more privileges on this repo so he could handle such things alone and speed up the process, if possible

**Comment by leerob** [comment]
NPM publish permission isn't given out to non-Vercel employees in the interest of security, as I'm sure you can understand 👍 He already has high permissions here - not sure what more you're thinking?

**Comment by robertsLando** [comment]
No worries I understand it :)

**Pull request merged**
