### PR TITLE
expected: add hashes of Node.js 16.0.0 binaries

### PR DESCRIPTION
**Pull request by jesec**
workflow: 7c8ca68ade5d3d4c70f8e94c8064115c00281415

runs:
- alpine: https://github.com/vercel/pkg-fetch/actions/runs/778165607
- linux: https://github.com/vercel/pkg-fetch/actions/runs/778165672
- linuxstatic: https://github.com/vercel/pkg-fetch/actions/runs/778165846
- macos: https://github.com/vercel/pkg-fetch/actions/runs/778166261
- win: https://github.com/vercel/pkg-fetch/actions/runs/778166018

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by jesec** [comment]
@leerob

When you have time, please release `3.0.4`, append changelog and upload the new Node 16 binaries to `v3.0` release. 

After that, we can prepare a new release for pkg as well. 

Note: It is OK to bump patch here, since we only add binaries (changing/deleting them would require minor).

**Comment by leerob** [comment]
@jesec Do you have permission to create a release? I only need to publish the release to NPM permission wise if so.

**Comment by jesec** [comment]
> @jesec Do you have permission to create a release? I only need to publish the release to NPM permission wise if so.

I do have the privileges to create/update Git tags and Github releases. Yeah, I can do those, but I guess only you can bump the version and release to npm.

**Comment by leerob** [comment]
@jesec Would you mind taking care of creating the release? I will publish to NPM 👍

**Comment by jesec** [comment]
> @jesec Would you mind taking care of creating the release? I will publish to NPM 👍

Done. https://github.com/vercel/pkg-fetch/commit/fa6e45dbf48d07b21ba9fe47bfb136286d3c54ab

**Comment by leerob** [comment]
Did you update the changelog and binaries as well? I'm not seeing 3.0.4 reflected there.

**Comment by jesec** [comment]
> Did you update the changelog and binaries as well? I'm not seeing 3.0.4 reflected there.

It is done.

**Comment by leerob** [comment]
Released!

**Comment by jesec** [comment]
Though, in my opinion, security-wise it is sounder that a separate maintainer fetch binaries from CI, verify that hashes matched the ones in source code (committed by changes like #171), cut the release and upload binaries. 

This way we have at least two maintainers who have independently verified the binaries (one commits changes like #171, one uploads binaries).

**Comment by robertsLando** [comment]
Sounds good

**Pull request merged**
