### PR TITLE
Building s390x version in a Docker container

### PR DESCRIPTION
**Pull request by toddq**
I don't know how you build the binaries for releases, but this is what I had to do to cross-compile for the s390 architecture in a Docker container.  Maybe it'll be helpful for adding official s390 support to pkg.

### CODE REVIEW

**Comment by toddq** [comment]
Well, I finally got around to trying the resulting binary on an actual zLinux system today, and it doesn't actually execute (binary crashes).  

As long as I had some time on the system, I managed to get some build tools installed and did manage to build the patched node binaries for both 10.4.1 and 10.15.3, and confirmed that they both work.  So the issue is with my cross-compile environment.

In the process, I also learned the hard way that you can't use pkg to cross-package architectures, which doesn't seem to really be documented.  From my Mac I can pkg for win/linux x64, but not s390x, have to do it on the zLinux machine for that.  I don't know what magic the bytecode generation is doing to better understand that.

**Comment by leerob** [comment]
@jesec what are your thoughts on this?

**Comment by jesec** [comment]
I think none of us has (or has access to) an IBM z mainframe......

**Comment by jesec** [comment]
I don't think we can properly support the architecture unless someone generously grant us access to an actual `s390x` machine to run tests and debug when needed.

**Comment by leerob** [comment]
That was my thought as well. Going to close this 🙏

**Comment by xturtle** [comment]
Hello, I can access the s390x machine. How can I run test suites for runtime binary?

In fact, I'm facing the same problem:

> pkg@5.3.3
> Fetching base Node.js binaries to PKG_CACHE_PATH

> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.2","name":"node-v16.8.0-linux-s390x"}
> Building base binary from source:
  built-v16.8.0-linux-s390x
> Error! Not able to build for 'linux' here, only for 'alpine'

**Pull request closed without merging**
