### PR TITLE
patches: bump to 14.21.3, 16.19.1, 18.14.1, and 19.6.1

### LINKED ISSUE #275: need to enable support to node LTS 18.14.1

### PR DESCRIPTION
**Pull request by baparham**
Updates to that [recent security releases](https://nodejs.org/en/blog/vulnerability/february-2023-security-releases/) made by Node.js team, specifically around OpenSSL. See their blog post for details about the specific CVEs this resolves.

Fixes #275

### CODE REVIEW

**Comment by baparham** [comment]
hm, Node16 failed to print any output on the `applyPatches` test, almost like the output wasn't flushed to stdout or something, or there was a timeout or something. I can't exactly explain why it failed, but that's disappointing that it's flakey like that. I force pushed again with no changes and it passed the second time.

**Comment by baparham** [comment]
Running a full (non-ARM) set of builds to verify these patches still build based on this patch here: https://github.com/baparham/pkg-fetch/actions/runs/4203687943

**Comment by robertsLando** [comment]
Is this good to merge?

**Comment by baparham** [comment]
I don't think so, the builds on windows node 18 seem to have failed, so probably needs some due diligence

**Comment by baparham** [comment]
failures look unrelated, so I'll retry them when the other builds are done:

https://github.com/baparham/pkg-fetch/actions/runs/4203687943/jobs/7293401466#step:5:14

**Comment by robertsLando** [comment]
LMK

**Comment by baparham** [comment]
@robertsLando builds look clean, we can merge this in

**Pull request merged**
