### PR TITLE
patches: bump to 16.20.1

### PR DESCRIPTION
**Pull request by n0cloud**

### CODE REVIEW

**Comment by n0cloud** [comment]
I think this version is not yet available on nodejs.org (only on github). We'll have to run the CI later.

**Comment by robertsLando** [comment]
tests are failing

**Comment by NewEraCracker** [comment]
Hello,

Would it be possible, that after this is complete, besides releasing a newer pkg-fetch version on npm, to release also an update to pkg with this included?

And, in light of security updates this month (https://nodejs.org/en/blog/vulnerability/june-2023-security-releases), release the updated latest v18 and v20 versions (v19 is EOL) as well?

Thanks.

**Comment by n0cloud** [comment]
@robertsLando node 16.20.1 wasn't available on nodejs servers. Tests are passing now.

**Comment by baparham** [comment]
I'm testing the binary builds in my fork with your commit (and a bump for 18 also). https://github.com/baparham/pkg-fetch/actions/runs/5519442958

I think this can go in if those binaries for 16 build OK.

**Comment by baparham** [comment]
> I'm testing the binary builds in my fork with your commit (and a bump for 18 also). https://github.com/baparham/pkg-fetch/actions/runs/5519442958
> 
> I think this can go in if those binaries for 16 build OK.

something's up with the entire system I think though, since all the jobs are succeeding _way_ too fast, and when you go in to look at them the binaries are not building, with no debug information whatsoever :-(

**Pull request closed without merging**
