### PR TITLE
patches: add patch for node 19.6

### PR DESCRIPTION
**Pull request by phated**
I prepared a patch for node 19.6 and then linked/tested it within our project. These seem to work based on our usage.

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]

**Comment by robertsLando** [comment]
review this when possible @baparham

**Comment by baparham** [comment]
@phated thanks for the contribution! You may have better luck building the binaries in your fork if you also use the patch from #265 to enable building on linux after node LTS switched from 16x to 18x. There was also a weird windows error that I don't recognize but it seems unrelated to these changes...I'll try to reproduce in my fork.

What OS-arch are you testing within your project, so we know what's been 'manually tested' so to speak?

I'd like to see successful builds of each platform/node version combo before suggesting this should go in. I'll kick off some builds on my own to check this patch out as well.

**Comment by baparham** [comment]
I have a full set of builds (all except non-windows arm platforms) kicked off here with this patch: https://github.com/baparham/pkg-fetch/actions/runs/4103184419 to see how they all build, or if the errors I saw in Blaine's fork actions are reproducible.

**Comment by phated** [comment]
My manual test was on Mac Arm64. Thanks for the quick replies!

**Comment by phated** [comment]
Regarding the Windows failure, the dtrace and etw support was dropped in https://github.com/nodejs/node/commit/aa3a572e6bee116cde69508dc29478b40f40551a so the `noetw` arg is no longer needed in node 19+

I just pushed a commit that should fix it.

**Comment by robertsLando** [comment]
@baparham could you spawn new tests?

**Comment by baparham** [comment]
running here: https://github.com/baparham/pkg-fetch/actions/runs/4112226627

**Comment by robertsLando** [comment]
Perfect thanks LMK

**Comment by phated** [comment]
This run looks all green to me 🎉 https://github.com/baparham/pkg-fetch/actions/runs/4112226627

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by robertsLando** [comment]
@leerob kindly merge this 🙏🏼

**Comment by phated** [comment]
Anything else needed to land this?

**Comment by robertsLando** [comment]
@leerob ping

**Pull request merged**
