### PR TITLE
Allow additional Node configure args with PKG_BUILD_CONFIGURE_ARGS

### PR DESCRIPTION
**Pull request by mladkau**
This PR adds the ability to specify additional build options for the node build via an environment variable.

For example:
```
export PKG_BUILD_PARAM="--partly-static"
pkg . --build -t node14-linux-x64
```
This can be used to address: vercel/pkg#555
The added functionality is a bit wider than vercel/pkg-fetch/pull/72

### CODE REVIEW

**Comment by jesec** [comment]
@mladkau I made some updates: a. rename the env variable to `PKG_BUILD_CONFIGURE_ARGS`, 2. apply to windows build as well.

**Review by robertsLando — CHANGES_REQUESTED** [review]
This needs to be documented in pkg and/or here. Maybe in this section: https://github.com/vercel/pkg#environment (waiting for a pr there before merge)

**Comment by jesec** [comment]
> This needs to be documented in pkg and/or here. Maybe in this section: https://github.com/vercel/pkg#environment (waiting for a pr there before merge)

I lean toward hiding this as an advanced argument.

**Comment by robertsLando** [comment]
I understand it but we should start document more things in both pkg and pkg-fetch projects otherwise it could be hard for new devs to start developing or even users that are looking for those advanced options need to read the code in order to know them

**Comment by leerob** [comment]
Any update here?

**Comment by robertsLando** [comment]
I think this could land but needs docs...

**Comment by jesec** [comment]
> > This needs to be documented in pkg and/or here. Maybe in this section: https://github.com/vercel/pkg#environment (waiting for a pr there before merge)
> 
> I lean toward hiding this as an advanced argument.

^

Documenting it means that we are supposed to support it in some ways, but we can't support every exotic Node configure flag (and combination of) out there. The custom binaries would not be supported by us in any way. As such, I think this should be a hidden undocumented option.

**Review by robertsLando — APPROVED** [review]

**Comment by robertsLando** [comment]
@leerob Could we merge this?

**Comment by robertsLando** [comment]
@jesec

**Pull request closed without merging**
