### PR TITLE
Add support for linuxstatic armv7 binaries

### PR DESCRIPTION
**Pull request by Hypfer**
As discussed in https://github.com/vercel/pkg-fetch/issues/109

### CODE REVIEW

**Comment by Hypfer** [comment]
Built binaries:

https://github.com/JockulatorStudiosNorth/pkg-fetch/actions/runs/886339358

**Comment by xyklex** [comment]
@Hypfer in theory by just adding the hashes of the binaries into `expected.ts` should this work?

**Comment by xyklex** [comment]
binaries work, thanks @Hypfer

**Comment by jesec** [comment]
Great work. Though, I will probably try `armv7l-linux-musleabihf` toolchain. That should imply `march` and stuff, and remove the need for the flags.

**Pull request merged**
