### PR TITLE
Simplify expected name of release asset

### PR DESCRIPTION
**Pull request by jesec**
uploaded-v2.6-node-v14.16.0-linux-x64

->

node-v14.16.0-linux-x64

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
LGTM

**Review by leerob — CHANGES_REQUESTED** [review]
My guess is the version tag is in this for a reason. Does `pkg` expect this to be there?

**Comment by jesec** [comment]
> My guess is the version tag is in this for a reason. Does `pkg` expect this to be there?

`pkg` does not use remotePlace. The only user of the name is https://github.com/vercel/pkg-fetch/blob/e314198e538d55d0eafba15e064ca027e584d313/lib/index.ts#L25. 

IMO there is no need to specify the tag again in the name of assets.

**Comment by robertsLando** [comment]
This was for the old behaviour now we directly upload assets to the correct release tag so there is no need of that

**Review by leerob — APPROVED** [review]
Got it. Let's make sure we mention this in the changelog 😄

**Pull request merged**
