### PR TITLE
expected: add hashes of Node v14.17.0 binaries

### PR DESCRIPTION
**Pull request by jesec**
- alpine: https://github.com/vercel/pkg-fetch/actions/runs/838900430
- linux: https://github.com/vercel/pkg-fetch/actions/runs/838900527
- linuxstatic: https://github.com/vercel/pkg-fetch/actions/runs/838900585
- macos: https://github.com/vercel/pkg-fetch/actions/runs/838900726
- win: https://github.com/vercel/pkg-fetch/actions/runs/838900655
- macos-arm64: manual

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]

**Comment by jesec** [comment]
@leerob @robertsLando :

We are ready for a v3.1.0 release. What do you think?

**Comment by leerob** [comment]
Sounds great! If y'all can handle getting the release ready, I will publish to NPM 😄

**Comment by robertsLando** [comment]
Go for it 🚀

**Comment by jesec** [comment]
🔥  It is done: https://github.com/vercel/pkg-fetch/releases/tag/v3.1 .

**Comment by jesec** [comment]
ping. @leerob

**Comment by leerob** [comment]
Sorry, was tied up with [nextjs.org/conf](https://nextjs.org/conf). Releasing now!

**Pull request merged**
