### PR TITLE
Revive cross compile and bump patches to latest

### LINKED ISSUE #276: Re-enable cross compiling for ARM
Right now we have no runners for arm builds, and the cross compiling stopped working a year or two ago (hence the introduction of @jesec fork's self-hosted arm runners), so maybe if somebody needs that they could work up a PR helping re-enable cross compiling from the steps outlined at [Node.js's BUILDING.md file](https://github.com/nodejs/node/blob/main/BUILDING.md)

_Originally posted by @baparham in https://github.com/vercel/pkg-fetch/issues/257#issuecomment-1433740037_

Any help anyone can provide to work up a PR re-enabling cross compiling following the directions at the Node.js building.md file would be greatly appreciated.

Presumably you can just fork the repo, enable actions in your repo, and run the builds yourself on GitHub's hosted runners to verify things work as expected as you develop your PR.

### PR DESCRIPTION
**Pull request by baparham**
- [X] This re-enables cross-compiling for ARM on x86, using the fix proposed in https://github.com/nodejs/node/pull/45756
 - [X] Bumps patches to 18.15.0 and 19.7.0.
 - [X] Adds a `build-all.yml` workflow to kick off and wait for all assets to build. To be added on to later with some more automated hash checking, perhaps some more tests (at least on x86) to ensure the built binaries are functional, etc.

There is currently a debug commit at the end to allow me to run the full build-all workflow to build all current assets on push to this `revive-cross-compile` branch, which I'll take out once I see the builds all succeed.

This would fix #276

### CODE REVIEW

**Comment by baparham** [comment]
Full build workflow running over in my fork for this branch here: https://github.com/baparham/pkg-fetch/actions/runs/4368413726

That really needs to pass to be sure the builds aren't broken, but I also have no way of actually runtime testing the arm binaries. Can someone else help out with testing those out once they are built to be sure ARM builds are in fact still working when cross compiled?

**Comment by robertsLando** [comment]
@baparham I can

**Comment by mertushka** [comment]
🤞

**Comment by ospencer** [comment]
Hey @baparham, I tested these on an M1 Mac using Docker, and they all appear to work. Here's a repo if anyone wants to reproduce: https://github.com/ospencer/test-pkg-fetch

It's a pretty basic hello world smoke test, but I figured that was sufficient.

**Comment by ospencer** [comment]
(To clarify, specifically I tested the Linux arm64 binaries—not sure if you need alpine, Windows, and friends tested too.)

**Comment by baparham** [comment]
Seems to be enough confirmation for me, @robertsLando shall we merge this in?

**Comment by baparham** [comment]
ah, not quite yet, I  need to drop the last debug commit first, I'll push again

**Comment by robertsLando** [comment]
Sorry for late feedback, have been very busy last weeks, yeah let's do this :)

**Review by robertsLando — APPROVED** [review]

**Comment by phated** [comment]
@robertsLando Are you also planning to do a release? 🙏

**Comment by mertushka** [comment]
Release wouldnt hurt 🙏

**Comment by robertsLando** [comment]
Wish I could do it, don't have the privileleges, need to ask @leerob via private email. @baparham Would you like to inform him? This should be a minor

**Comment by baparham** [comment]
Yeah, I'll reach out to him. In the meantime we could probably try and sneak in the latest 19.8.1 patch set too while we wait till US west coast time.

**Pull request merged**
