### PR TITLE
Specify a custom node binary with PKG_NODE_PATH

### PR DESCRIPTION
**Pull request by shawwn**
(This is useful for packaging a debug build of node.)

### CODE REVIEW

**Comment by jpx83** [comment]
@igorklopov  Can you have a look regarding this new feature? It will be very useful! Thank you.

**Comment by rauchg** [comment]
Can we document the flag in README?

**Comment by leerob** [comment]
Closing as inactive, feel free to open a new PR and we can get this through 🙏

**Comment by OmgImAlexis** [comment]
@leerob with this only being a 2 line change is there any reason not to allow this?

**Comment by OmgImAlexis** [comment]
> @OmgImAlexis there hadn't been any activity in years here. Is there an open issue related to this - or how did you find this? Happy to reconsider if multiple people are interested.

I've been subscribed for about a year. There's no activity as you'll find most long terms GitHub users won't comment as they're met with the "don't +1 this" instead we just subscribe. I assumed the PR was good to go and just hadn't been merged.

My issue was wanting to pass in a custom version for development as someone else stated.

**Comment by leerob** [comment]
@OmgImAlexis Ahh, got it! In that case, happen to re-open.

**Comment by leerob** [comment]
For more clarity, this needs:

- Documentation added to the README explaining how to use the flag
- Merge conflicts resolved

And then I will +1 and merge/release!

**Comment by robertsLando** [comment]
Docs should be added on pkg readme, in this section: https://github.com/vercel/pkg#environment

**Comment by baparham** [comment]
is anyone still interested in this?

**Comment by robertsLando** [comment]
For anyone that is enterested in this project, giving that I don't receive any feedback from Vercel anymore, I created my own forks of both pkg and pkg-fetch:

[yao-pkg/pkg-fetch](https://github.com/yao-pkg/pkg-fetch)
[yao-pkg/pkg](https://github.com/yao-pkg/pkg)

If someone is interested in helping me create a PR or move your active PR to those repositories.

Thanks 🙏🏼

**Comment by robertsLando** [comment]
This has been added by: https://github.com/yao-pkg/pkg-fetch/pull/7

**Pull request closed without merging**
